# Generated by Django 5.2.1 on 2025-07-09 14:26
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255, blank=True)),
                ('logo_url', models.URLField(max_length=500, blank=True, null=True)),
                ('website', models.URLField(max_length=255, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(max_length=500, blank=True, null=True)),
                ('website', models.URLField(max_length=255, blank=True, null=True)),
                ('industry', models.CharField(max_length=100, blank=True)),
                ('location', models.CharField(max_length=255, blank=True)),
                ('size', models.CharField(max_length=20, blank=True)),
                ('social_links', models.JSONField(default=dict, blank=True)),
                ('gallery_urls', models.JSONField(default=list, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(unique=True, max_length=254, verbose_name='email address')),
                ('user_type', models.CharField(max_length=10, default='student')),
                ('full_name', models.CharField(max_length=255, blank=True)),
                ('profile_picture_url', models.URLField(max_length=500, blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(related_name='user_set', to='auth.Group', blank=True)),
                ('user_permissions', models.ManyToManyField(related_name='user_set', to='auth.Permission', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile')),
                ('university', models.ForeignKey(null=True, blank=True, to='accounts.university', on_delete=django.db.models.deletion.SET_NULL)),
                ('major', models.CharField(max_length=100, blank=True)),
                ('graduation_year', models.PositiveIntegerField(null=True, blank=True)),
                ('gpa', models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)),
                ('skills', models.JSONField(default=list, blank=True)),
                ('interests', models.JSONField(default=list, blank=True)),
                ('career_preferences', models.JSONField(default=dict, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(max_length=255, blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_text', models.TextField(blank=True)),
                ('is_parsed', models.BooleanField(default=False)),
                ('embedding', models.JSONField(null=True, blank=True)),
                ('student_profile', models.ForeignKey(to='accounts.studentprofile', on_delete=django.db.models.deletion.CASCADE, related_name='resumes')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('user', models.OneToOneField(primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile')),
                ('company', models.ForeignKey(null=True, blank=True, to='accounts.company', on_delete=django.db.models.deletion.CASCADE)),
                ('role', models.CharField(max_length=100, blank=True)),
                ('is_company_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityStaffProfile',
            fields=[
                ('user', models.OneToOneField(primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE, related_name='university_staff_profile')),
                ('university', models.ForeignKey(to='accounts.university', on_delete=django.db.models.deletion.CASCADE)),
                ('role', models.CharField(max_length=100, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyJoinRequest',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('status', models.CharField(max_length=10, default='PENDING')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests')),
                ('company', models.ForeignKey(to='accounts.company', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityJoinRequest',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('status', models.CharField(max_length=10, default='PENDING')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE, related_name='university_join_requests')),
                ('university', models.ForeignKey(to='accounts.university', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests')),
            ],
        ),
    ] 