# Generated by Django 5.2.1 on 2025-07-14 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_options_user_first_name_user_last_name_and_more'),
        ('jobs', '0002_remove_old_career_fair_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('banner_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('floor_plan_url', models.URLField(blank=True, max_length=500, null=True)),
                ('host_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_fairs', to='accounts.university')),
            ],
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='accounts.company')),
                ('jobs', models.ManyToManyField(blank=True, related_name='booths', to='jobs.job')),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='career_fairs.careerfair')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_students', to='career_fairs.booth')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('booth', 'student')},
            },
        ),
    ]
