# Generated by Django 5.2.1 on 2025-07-14 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career_fairs', '0001_initial'),
        ('accounts', '0003_alter_user_options_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('host_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_fairs', to='accounts.university')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('banner_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('floor_plan_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
