# Generated by Django 5.2.1 on 2025-07-14 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career_fairs', '0002_career_fair'),
        ('accounts', '0003_alter_user_options_user_first_name_user_last_name_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='career_fairs.careerfair')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_booths', to='accounts.company')),
                ('jobs', models.ManyToManyField(blank=True, related_name='career_fair_booths', to='jobs.job')),
            ],
        ),
    ]
