# Generated by Django 5.2.1 on 2025-07-14 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career_fairs', '0003_booth'),
        ('accounts', '0003_alter_user_options_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_students', to='career_fairs.booth')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='accounts.user')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('booth', 'student')},
            },
        ),
    ]
