# Generated by Django 5.2.1 on 2025-07-14 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_fairs', '0004_student_interest'),
        ('jobs', '0002_remove_old_career_fair_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booth',
            name='height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booth',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='width',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booth',
            name='x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth',
            name='y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careerfair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerfair',
            name='grid_height',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='careerfair',
            name='grid_width',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='careerfair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='booths', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='booth',
            unique_together={('career_fair', 'x', 'y')},
        ),
    ]
