# Generated by Django 5.2.1 on 2025-07-14 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_first_name_user_last_name_and_more'),
        ('career_fairs', '0005_booth_created_at_booth_height_booth_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='career_fair',
            new_name='fair',
        ),
        migrations.RemoveField(
            model_name='careerfair',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='careerfair',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='careerfair',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='careerfair',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careerfair',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='careerfair',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='booth',
            unique_together={('fair', 'company')},
        ),
    ]
