# Generated by Django 5.2.1 on 2025-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_fairs', '0006_rename_career_fair_booth_fair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfair',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='careerfair',
            name='start_date',
            field=models.DateField(),
        ),
    ]
