# Generated by Django 5.2.1 on 2025-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_fairs', '0007_alter_careerfair_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='booth_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
