# Generated by Django 5.2.1 on 2025-07-16 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_add_report_generated_to_aiinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='audio_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interviewreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ] 