# Generated by Django 5.2.1 on 2025-07-16 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_aiinterviewreport_refactor'),
    ]

    operations = [
        # Remove any unique_together or constraints referencing 'application' on AIInterviewReport
        # No operations needed if there are no valid constraints left
    ] 