# Generated by Django 5.2.1 on 2025-07-17 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_aiinterviewreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiinterviewreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aiinterview',
            name='audio_file_url',
        ),
        migrations.AlterField(
            model_name='aiinterview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiinterviewreport',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.aiinterview'),
        ),
        migrations.AlterField(
            model_name='aiinterviewreport',
            name='model_name',
            field=models.CharField(help_text="Version of the model used (e.g., 'gemini-1.5-pro').", max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('INTERVIEWED', 'Interviewed'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_data', models.JSONField(help_text='Comprehensive employer-facing interview report data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', help_text='Version of the report format/LLM prompt.', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_reports', to='jobs.application')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_report', to='jobs.aiinterview')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('interview', 'application')},
            },
        ),
    ]
